<?php
/**
 * Simple Test Module - No Database
 * Demonstrates how to create hooks that just return hardcoded content
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

class SimpleTest extends Module
{
    public function __construct()
    {
        $this->name = 'simpletest';
        $this->tab = 'front_office_features';
        $this->version = '1.0.0';
        $this->author = 'QloApps Test';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = array('min' => '1.6', 'max' => _PS_VERSION_);
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Simple Test Module');
        $this->description = $this->l('Simple module for testing without database queries');
    }

    public function install()
    {
        return parent::install()
            && $this->registerHook('displayHome')
            && $this->registerHook('displayHomeTabContent')
            && $this->registerHook('displayHeader');
    }

    public function uninstall()
    {
        return parent::uninstall();
    }

    /**
     * Hook for displayHome - just returns simple HTML
     */
    public function hookDisplayHome($params)
    {
        return '
        <div style="background: #fff3cd; padding: 15px; border: 1px solid #ffc107; margin: 10px 0;">
            <h3>🏨 Simple Hotel Welcome</h3>
            <p>Welcome to our test hotel! This content comes from a simple hook.</p>
            <p><strong>No database queries involved!</strong></p>
            <p>Current time: ' . date('H:i:s') . '</p>
        </div>';
    }

    /**
     * Hook for displayHomeTabContent - returns tab content
     */
    public function hookDisplayHomeTabContent($params)
    {
        $content = '
        <div class="tab-pane" id="simple-content">
            <div style="background: #d1ecf1; padding: 15px; border: 1px solid #bee5eb;">
                <h4>📋 Simple Tab Content</h4>
                <p>This is content for the home tab - generated by simple hook!</p>
                <ul>
                    <li>✅ Module loaded successfully</li>
                    <li>✅ Hook executed without errors</li>
                    <li>✅ No PostgreSQL queries needed</li>
                    <li>✅ Just pure PHP output</li>
                </ul>
                <p><em>Generated at: ' . date('Y-m-d H:i:s') . '</em></p>
            </div>
        </div>';
        
        return $content;
    }

    /**
     * Hook for displayHeader - adds simple CSS
     */
    public function hookDisplayHeader($params)
    {
        return '<style>
            .simple-test { background: #f8f9fa; padding: 10px; border-radius: 5px; }
        </style>';
    }
}
?>